---
title: "Expose Master Thesis Lepke"
output: pdf_document
---
Short summary:
Improve Climate Model future projections by 
using obersvational data and Machine Learning
With future climate change, droughts in the Amazon forest may become more
frequent and/or severe. Droughts can turn Amazon regions from
rain forest into savanna, leading to high amounts of carbon
released into the atmosphere.
Past research has shown that there is a relatioship between
Sea Surface Temperatures (SSTs) in the Tropical Atlantic/Pacific and
precipation in the Amazon.
Step one in my thesis will be to quantify this relationship further,
using different approaches and compare them to each other.
So I am trying to find a predictive (interpretable) model
that can predict precipation from SST time series and possibly other variables.
If such a mechanism is found it can be used as a so called "emergent
constraint".
Since different climate models give different answers about future climate change,
there is a need to narrow the so called "spread".
Here we try to constrain this spread by using information from observations.
We can evaluate a climate models realism by comparing it's simulated variable
to actual observed variables. While assuming that models that simulate present climate
well, simulate future climate variables well, too.
The models future projections then get rescaled according to how well they fit
the present climate variable.
(Much simplified) We rescale a models future projection (i.e rain) by how well it fits the current observable data.
Then we can use a ML approach to
learn function: 
f(model data of present climate variable) = rescaled model projection and
predict: f(observed data of present climate variable) = projection of
validate with CV etc.
This can be learned f.e by Gradient Boosting Regression Trees


Longer explanation:
Motivation:
Related Work SST amazonas:
Emergent Constraint:
Related Work GBRT:
The data:
Next steps

