default:
  features_cv_path: "data/processed/small_sst_cv.rds"
  target_cv_path: "data/processed/precip_cv.rds"
  features_eval_path: "data/processed/small_sst_eval.rds"
  target_eval_path: "data/processed/precip_eval.rds"
  save_folder: "fused-cv-test"
  nfold:  5
  size_train:  60
  size_test:  14
  small:  TRUE
  model:  "fused"
  maxsteps:  10
  gamma:  0
  standardize_response:  TRUE
  standardize_features:  FALSE
  include_ts_vars:  FALSE
  diff_features:  FALSE
  des_features:  FALSE
