# Noclust Fused 5k

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```


```{r}
library(patchwork)
library(ggpubr)
library(raster)
library(glmnet)
library(Hmisc)
source("../code/R/helper-functions.R")
```

```{r}
# inspect error plots
# inspect coef plots
# inspect prediction plots
# length(ids$train$Training060)
# length(ids$test$Testing060)
```
```{r}
path_to_model_folder <- "../results/CV-fused/noclust-large-fused-5k/"
```

## Error plots

<!-- ```{r} -->
<!-- err_mat <- readRDS("../results/CV-lasso/cv-lasso-og-data-16-06-22/err-mat.rds") -->
<!-- #err_mat <- sqrt(err_mat) -->
<!-- err_mat <- err_mat[1:60,] -->
<!-- ``` -->

<!-- ```{r} -->
<!-- lambda_id <- c(1:60) -->
<!-- mse <- apply(err_mat, 1, mean) -->
<!-- b <- mse -->
<!-- bplus <- apply(err_mat, 1, max) -->
<!-- bmin <- apply(err_mat, 1, min) -->
<!-- errbar(lambda_id, mse, b+bplus, b-bmin) -->
<!-- ``` -->
```{r}
err_mat <- readRDS(paste0(path_to_model_folder, "/err-mat.rds"))
#lambdas <- readRDS(paste0(path_to_model_folder, "/lambda-vec.rds"))
```


```{r, fig.cap="Mean squared error of the 5-fold blocked cross validation for a range of lambda values on the log scale. The points in the middle represent the average MSE for the respective lambda, the errorbars give the MSE +/- one standard deviation. The dotted line shows the lambda for which minimum MSE was obtained."}
err_line_plot <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-line-plot.rds"))
err_line_plot
# a <- ggplot_build(err_bars_plot)
```


```{r , fig.cap="MSE of the CV for the different lambda values on the a log scale. The red dotted line shows the lambda for which minimum MSE was obtained."}
p1 <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-plot-fold1.rds"))
p2 <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-plot-fold2.rds"))
p3 <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-plot-fold3.rds"))
p4 <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-plot-fold4.rds"))
p5 <- readRDS(paste0(path_to_model_folder, "/err-mat-plots/err-plot-fold5.rds"))

p1 + p2 + p3 + p4 + p5

```

```{r}
err_mat_p_list <- list(p1,p2,p3,p4,p5)
err_mat_resc_list <- replot_err_mat(err_mat_p_list)
```

```{r , fig.cap="MSE of the CV for the different lambda values on the a log scale. The red dotted line shows the lambda for which minimum MSE was obtained. See @\ref(fig:err-folg-lasso-og), but this time the y-axis has the same range for all plots."}
err_mat_resc_list[[1]] + err_mat_resc_list[[2]] + err_mat_resc_list[[3]] + err_mat_resc_list[[4]] + err_mat_resc_list[[5]]
```

Below we can see the minimum MSE for each fold.
```{r}
apply(err_mat, 2, min)
```
And which lambda in the lambda vector resulted in the lowest prediction error on the folds´ test set.

```{r}
#apply(err_mat, 2, function(x) lambdas[which.min(x)])
```

## Coefficient plots

```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
pc1 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-fold-1.rds"))
pc1
```
```{r}
rm(pc1)
```


```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
pc2 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-fold-2.rds"))
pc2
```
```{r}
rm(pc2)
```


```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
pc3 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-fold-3.rds"))
pc3
```

```{r}
rm(pc3)
```

```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
pc4 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-fold-4.rds"))
pc4
```
```{r}
rm(pc4)
```


```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
pc5 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-fold-5.rds"))
pc5
```
```{r}
object.size(pc5)
dim(pc5$data)
pc5$data
?object.size
```


```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
rm(pc5)
```


```{r , fig.cap="Coefficient map plot for the different folds. Longitude and Latitude on the x and y-axis respectively. Positive values are coloured in blue, negative values in red."}
l <- list(pc1,pc2,pc3,pc4,pc5)
a1 <- ggarrange(plotlist = l, ncol = 3, nrow = 2,
         common.legend = TRUE)
a1
```
```{r}
pc1 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-drop-out-fold-1.rds"))
pc2 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-drop-out-fold-2.rds"))
pc3 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-drop-out-fold-3.rds"))
pc4 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-drop-out-fold-4.rds"))
pc5 <- readRDS(paste0(path_to_model_folder, "/coef-plots/coef-plot-drop-out-fold-5.rds"))

l2 <- list(pc1,pc2,pc3,pc4,pc5)
a2 <- ggarrange(plotlist = l2, ncol = 3, nrow = 2,
         common.legend = TRUE)
a2
```


## Inspect predictions from each fold

Following we inspect the folds precipitation time series and
the predictions made by the model.

```{r}
pred_plot_1 <- readRDS(paste0(path_to_model_folder, "/pred-plots/pred-plot-fold-1.rds"))
#pred_plot_1
mse_1 <- get_mse_from_pred_plot(pred_plot_1)
pred_plot_2 <- readRDS(paste0(path_to_model_folder, "/pred-plots/pred-plot-fold-2.rds"))
#pred_plot_2
mse_2 <- get_mse_from_pred_plot(pred_plot_2)
pred_plot_3 <- readRDS(paste0(path_to_model_folder, "/pred-plots/pred-plot-fold-3.rds"))
#pred_plot_3
mse_3 <- get_mse_from_pred_plot(pred_plot_3)
pred_plot_4 <- readRDS(paste0(path_to_model_folder, "/pred-plots/pred-plot-fold-4.rds"))
#pred_plot_4
mse_4 <- get_mse_from_pred_plot(pred_plot_4)
pred_plot_5 <- readRDS(paste0(path_to_model_folder, "/pred-plots/pred-plot-fold-5.rds"))
#pred_plot_5
mse_5 <- get_mse_from_pred_plot(pred_plot_5)
pred_plot_list <- list(pred_plot_1,pred_plot_2,pred_plot_3,pred_plot_4,pred_plot_5)
#lapply(pred_plot_list, get_mse_from_pred_plot)
```
```{r , fig.cap="Precipitation prediction and target values in the test set in each fold. Predictions in red and target values in black."}
pred_plot_1 + pred_plot_2 + pred_plot_3 + pred_plot_4 +
  pred_plot_5
```


```{r}
best_l_res <- readRDS(paste0(path_to_model_folder, "best-lambda-res.rds"))
best_l_res
```

```{r}
err_line_full <- readRDS(paste0(path_to_model_folder, "err-mat-plots/error-line-plot-full.rds"))
err_line_full
```


```{r}
pred_plot_full <- readRDS(paste0(path_to_model_folder, "pred-plots/pred-plot-full.rds"))
attr(pred_plot_full, "mse")
pred_plot_full
```

```{r}
coef_full <- readRDS(paste0(path_to_model_folder, "coef-plots/coef-plot-full.rds"))
coef_full
```
```{r}
coef_full_drop <- readRDS(paste0(path_to_model_folder, "coef-plots/coef-plot-drop-out-full.rds"))
coef_full_drop

```

```{r}
# TESTING
# 
rnd <- readRDS("../results/CV-fused/large-fused-5k/all_preds_full_model.rds")
pp <- readRDS("../data/processed/precip_eval.rds")

err <- apply(rnd$fit, 2, function(x) comp_mse(x, pp))
which.min(err)
plot(ts(rnd$fit[,5000]))
plot(ts(pp))
```


