# Lasso deseasonalised
```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```


```{r}
library(patchwork)
library(ggpubr)
library(raster)
library(glmnet)
library(Hmisc)
source("../code/R/helper-functions.R")
```

```{r}
err_mat <- readRDS("../results/CV-lasso/cv-lasso-des-data-08-11-21/err-mat.rds")

```


```{r}
# load data
target_path <- "../data/processed/deasonalised_precip_aggregated.rds"
features_path <- "../data/processed/deseasonalised_sst.rds"
target <- load_data(target_path)
target <- apply(getValues(target), 2, mean)
features <- load_data(features_path, "sst")
features <- t(features)
features <- prepare_sst(features)
dim(features)
```


```{r}
# get indices
lambdas <- readRDS("../results/CV-lasso/cv-lasso-des-data-08-11-21/lambda-vec.rds")
ids <- readRDS("../results/CV-lasso/cv-lasso-des-data-08-11-21/index-list.rds")
```


```{r}
f1_train <- ids$train$Training060
f1_test <- ids$test$Testing060
x1_train <- features[f1_train,]
y1_train <- target[f1_train]
x1_test <- features[f1_test,]
y1_test <- target[f1_test]
min1 <- which.min(err_mat[,1])
m1 <- glmnet(x1_train, y1_train, lambda=rev(lambdas)[min1])
preds1 <- predict(object = m1, newx = x1_test)
df <- data.frame(preds = preds1, target = y1_test, check.names=TRUE)
ggplot() + geom_line(data = df, mapping = aes(x=1:14, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:14, y=target))
```

```{r}
f2_train <- ids$train$Training134
f2_test <- ids$test$Testing134
x2_train <- features[f2_train,]
y2_train <- target[f2_train]
x2_test <- features[f2_test,]
y2_test <- target[f2_test]
min2 <- which.min(err_mat[,2])
m2 <- glmnet(x2_train, y2_train, lambda=rev(lambdas)[min2])
preds2 <- predict(m2, newx = x2_test)
df <- data.frame(preds = preds2, target = y2_test)
ggplot() + geom_line(data = df, mapping = aes(x=1:14, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:14, y=target))
```
```{r}
f3_train <- ids$train$Training208
f3_test <- ids$test$Testing208
x3_train <- features[f3_train,]
y3_train <- target[f3_train]
x3_test <- features[f3_test,]
y3_test <- target[f3_test]
min3 <- which.min(err_mat[,3])
m3 <- glmnet(x3_train, y3_train, lambda=rev(lambdas)[min3])
preds3 <- predict(m3, newx = x3_test)
df <- data.frame(preds = preds3, target = y3_test)
ggplot() + geom_line(data = df, mapping = aes(x=1:14, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:14, y=target))
```
```{r}
f4_train <- ids$train$Training282
f4_test <- ids$test$Testing282
x4_train <- features[f4_train,]
y4_train <- target[f4_train]
x4_test <- features[f4_test,]
y4_test <- target[f4_test]
min4 <- which.min(err_mat[,4])
m4 <- glmnet(x4_train, y4_train, lambda=rev(lambdas)[min4])
preds4 <- predict(m4, newx = x4_test)
df <- data.frame(preds = preds4, target = y4_test)
ggplot() + geom_line(data = df, mapping = aes(x=1:14, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:14, y=target))
```

```{r}
f5_train <- ids$train$Training356
f5_test <- ids$test$Testing356
x5_train <- features[f5_train,]
y5_train <- target[f5_train]
x5_test <- features[f5_test,]
y5_test <- target[f5_test]
min5 <- which.min(err_mat[,5])
m5 <- glmnet(x5_train, y5_train, lambda=rev(lambdas)[min5])
preds5 <- predict(m5, newx = x5_test)
df <- data.frame(preds = preds5, target = y5_test)
ggplot() + geom_line(data = df, mapping = aes(x=1:14, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:14, y=target))
```



## Inspect predictions from best CV-lambda

```{r}
# fit model with best lambda
#which.min(b)
lambdas <- readRDS("../results/CV-lasso/cv-lasso-des-data-08-11-21/lambda-vec.rds")
```

```{r}
minmin <- which.min(apply(err_mat, 1, mean))
#minmin <- 45
best_lambda <- rev(lambdas)[minmin]
dim(features)
m_full <- glmnet(features[1:370,], target[1:370], lambda = best_lambda)
preds_full <- predict(m_full, newx = features[371:432,],
                      lambda = best_lambda)
df <- data.frame(preds = preds_full, target = target[371:432])
dim(preds_full)
ggplot() + geom_line(data = df, mapping = aes(x=1:62, y=s0, colour = "blue")) +
  geom_line(data = df, mapping= aes(x=1:62, y=target))

```

```{r}
sqrt(mean((df$s0 - df$target)^2))
```
```{r}
mean((df$s0 - df$target)^2)
```



