---
author: "Dario Lepke"
site: bookdown::bookdown_site
output_dir: "thesis-book"
output:
  bookdown::pdf_book:
    split_bib: FALSE
    latex_engine: xelatex
    includes:
      in_header: "preamble-only.tex"
      before_body: "body-only.tex"
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "preamble-only.tex"
      before_body: "body-only.tex"
  bookdown::gitbook:
    # split_by: section
    split_bib: FALSE
  bookdown::pdf_document2:
    split_bib: FALSE
    latex_engine: xelatex
    includes:
      in_header: "preamble-only.tex"
      before_body: "body-only.tex"
  bookdown::html_document2:
bibliography: ref-lib.bib
biblio-style: apalike
link-citations: yes
documentclass: book
lof: yes
lot: yes
---
# Introduction {-}

```{r, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE, message = FALSE, out.width = '50%', fig.align = 'center')
options(knitr.duplicate.label = "allow")
```

With future climate change droughts in the Amazon forest may become more
frequent and/or severe. Droughts can turn Amazon regions from rain forest into
savanna, leading to high amounts of carbon released into the atmosphere.
Therefore, predicting future droughts and understanding the underlying mechanisms 
is of great interest. @ciemer2020early, established an 
early warning indicator for droughts in the central Amazon basin (CAB), based on tropical Atlantic sea surface 
temperatures (SSTs). Inspired by their work, the aim of this thesis is to build up on this work and improve its
predictive power by using different statistical methods.
Here we seek to build a model that is able to predict monthly precipitation based on the
sea surface temperatures. 
Also we want to identify those sea regions that are most important for doing so, making interpretability a point of interest, too.
Firstly we will analyze the data descriptively to 
explore patterns and spatial dependencies.
This includes a cluster analysis of the precipitation data
in the central Amazon basin.
Following we will compare two different regression approaches
and their capability to predict precipitation as well as their interpretability of the SST regions selected by them.
The first model is the lasso as proposed by @tibshirani1996regression. Comparing different model specifications we will carry on the findings from the lasso
and fit a (sparse) fused lasso on the data (@tibshirani2005sparsity).
Both models will be evaluated using a 5-fold forward selection,
a model evaluation technique that takes into account the time dependencies present in the data at hand.
We conclude with a summary of the findings in this work 
and give an overview of strengths and limitations of the approaches used together with ideas for future research.


This thesis was written and supervised in cooperation with Dr. Niklas Boers from the Potsdam Institute for Climate Impact Research (@PIC) and Dr. Fabian Scheipl (LMU)
